### ISSUE TITLE
ArgumentError: argument -q/--queue-class: conflicting option string: -q

### ISSUE THREAD

**Issue by pida42** [rq/rq-scheduler#177]
Getting this error after the "ArgumentError: argument -q/--queue-class: conflicting option string: -q" commit *eaa31df*

```
Traceback (most recent call last):
File "/usr/local/bin/rqscheduler", line 11, in <module>
  sys.exit(main())
File "/usr/local/lib/python3.5/dist-packages/rq_scheduler/scripts/rqscheduler.py", line 31, in main
  parser.add_argument('-q', '--queue-class', help='Custom RQ Queue class')
File "/usr/lib/python3.5/argparse.py", line 1353, in add_argument
  return self._add_action(action)
File "/usr/lib/python3.5/argparse.py", line 1716, in _add_action
  self._optionals._add_action(action)
File "/usr/lib/python3.5/argparse.py", line 1557, in _add_action
  action = super(_ArgumentGroup, self)._add_action(action)
File "/usr/lib/python3.5/argparse.py", line 1367, in _add_action
  self._check_conflict(action)
File "/usr/lib/python3.5/argparse.py", line 1506, in _check_conflict
  conflict_handler(action, confl_optionals)
File "/usr/lib/python3.5/argparse.py", line 1515, in _handle_conflict_error
  raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -q/--queue-class: conflicting option string: -q
```

**Comment by Westfallx** [comment]
same problem here

**Comment by pida42** [comment]
My hotfix: 

```
pip3 uninstall -y rq-scheduler
pip3 install rq-scheduler==0.7.0
```
:-)

**Comment by ahmetkurukose** [comment]
same problem here. Thank you @pida42 for the workaround.

**Comment by pdoggi** [comment]
Me too! Thanks @pida42!
