### ISSUE TITLE
rqscheduler in CLI throws Redis ResponseError 

### ISSUE THREAD

**Issue by rachel1792** [rq/rq-scheduler#185]
When I type `rqscheduler` to kick off the scheduler, I get the following error:

```
Traceback (most recent call last):
  File "/Users/rachelkogan/xword-app/env/bin/rqscheduler", line 11, in <module>
    sys.exit(main())
  File "/Users/rachelkogan/xword-app/env/lib/python2.7/site-packages/rq_scheduler/scripts/rqscheduler.py", line 61, in main
    scheduler.run(burst=args.burst)
  File "/Users/rachelkogan/xword-app/env/lib/python2.7/site-packages/rq_scheduler/scheduler.py", line 413, in run
    if self.acquire_lock():
  File "/Users/rachelkogan/xword-app/env/lib/python2.7/site-packages/rq_scheduler/scheduler.py", line 79, in acquire_lock
    key, now, ex=expires, nx=True)
  File "/Users/rachelkogan/xword-app/env/lib/python2.7/site-packages/redis/client.py", line 1173, in set
    return self.execute_command('SET', *pieces)
  File "/Users/rachelkogan/xword-app/env/lib/python2.7/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/rachelkogan/xword-app/env/lib/python2.7/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/Users/rachelkogan/xword-app/env/lib/python2.7/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: wrong number of arguments for 'set' command
```

Here are the versions I have:
```
redis==2.10.6
rq==0.10.0
rq-scheduler==0.8.2
```

Any help would be appreciated! Let me know if you have any follow-up questions.

**Comment by adamrt** [comment]
Do you mind posting the relevant code to help debup.

What is `*pieces`?

**Comment by selwin** [comment]
I don't think this is an RQ related error.
